# Generated by Django 6.0.4 on 2026-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imge',
            field=models.ImageField(default=None, upload_to='project_image/'),
            preserve_default=False,
        ),
    ]
